drop table if exists accounts;

create table accounts (
id int generated by default as identity,
name varchar(100) not null,
balance dec(15,2) not null,
primary key(id)
);

insert into accounts(name, balance)
values('Conde', 500);

insert into accounts(name, balance)
values('João', 500000);

select * from accounts;